services:
  db_food:
    container_name: postgres_food
    image: postgres:latest
    volumes:
      - db_food:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - dbnet
    restart: unless-stopped
    environment:
      - POSTGRES_USER=RestoBebraFood
      - POSTGRES_PASSWORD=RestoBebraFood
      - POSTGRES_DB=db_food

  db_user:
    container_name: postgres_user
    image: postgres:latest
    volumes:
      - db_user:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - dbnet
    restart: unless-stopped
    environment:
      - POSTGRES_USER=RestoBebraFood
      - POSTGRES_PASSWORD=RestoBebraFood
      - POSTGRES_DB=db_user

  db_notification:
    container_name: postgres_notification
    image: postgres:latest
    volumes:
      - db_notification:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - dbnet
    restart: unless-stopped
    environment:
      - POSTGRES_USER=RestoBebraFood
      - POSTGRES_PASSWORD=RestoBebraFood
      - POSTGRES_DB=db_notification

  db_redis:
    container_name: db_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dbnet

  food-microservice:
    container_name: food-microservice
    image: "ghcr.io/jabaxnt/restorumba/food-microservice:latest"
    volumes:
      - .:/app
      - /app/target
    ports:
      - "8080:8080"
    networks:
      - dbnet
    depends_on:
      - db_food
      - db_redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_food:5432/db_food
      - SPRING_DATASOURCE_USERNAME=RestoBebraFood
      - SPRING_DATASOURCE_PASSWORD=RestoBebraFood
      - SPRING_REDIS_HOST=db_redis
      - SPRING_REDIS_PORT=6379

  user-microservice:
    container_name: user-microservice
    image: "ghcr.io/jabaxnt/restorumba/user-microservice:latest"
    volumes:
      - .:/app
      - /app/target
    ports:
      - "8081:8080"
    networks:
      - dbnet
    depends_on:
      - db_user
    environment:
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9093
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_user:5432/db_user
      - SPRING_DATASOURCE_USERNAME=RestoBebraFood
      - SPRING_DATASOURCE_PASSWORD=RestoBebraFood
      - ADMIN_USERNAME=ADMIN
      - ADMIN_PHONE=+77777777777
      - ADMIN_PASSWORD=ADMIN
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=414447960098-v41o6hhfulreq35e5sfjrf9vje38l8nt.apps.googleusercontent.com
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=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
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI={baseUrl}/login/oauth2/code/google

  notification-microservice:
    container_name: notification-microservice
    image: "ghcr.io/jabaxnt/restorumba/notification-microservice:latest"
    volumes:
      - .:/app
      - /app/target
    ports:
      - "8082:8080"
    networks:
      - dbnet
    depends_on:
      - db_notification
    environment:
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9093
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_notification:5432/db_notification
      - SPRING_DATASOURCE_USERNAME=RestoBebraFood
      - SPRING_DATASOURCE_PASSWORD=RestoBebraFood

  zookeeper:
    container_name: zookeeper
    image: 'confluentinc/cp-zookeeper:latest'
    ports:
      - "2181:2181"
    networks:
      - dbnet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: kafka
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - dbnet
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    networks:
      - dbnet
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

networks:
  dbnet:

volumes:
  db_food:
  db_user:
  db_notification: